--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,7 +8,7 @@
 
     strategy:
       matrix:
-        os: [macos-latest, windows-latest, [ubuntu-latest]
+        os: [macos-latest, windows-latest, ubuntu-latest]
         configuration: [release, debug]
 
     runs-on: ${{ matrix.os }}
@@ -51,5 +51,4 @@
     # Run the tests with Powershell syntax
     - name: Test (vs2019)
       if: runner.os == 'Windows'
-      run: "& ./bin/${{ matrix.configuration }}/test.exe"
-      +      run: "& ./bin/${{ matrix.configuration }}/test.exe"