--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -56,5 +56,4 @@
     # Run the tests with Powershell syntax
     - name: Test (vs2019)
       if: runner.os == 'Windows'
-      run: "& ./bin/${{ matrix.configuration }}/test.exe"
-      +      run: "& ./bin/${{ matrix.configuration }}/test.exe"